### ISSUE TITLE
Does not work with next/future/image

### ISSUE THREAD

**Issue by webcredo** [RyanClementsHax/storybook-addon-next#113] opened 2022-08-05 23:44 UTC
### Describe the bug

Storybook gives the error:

`The "next/future/image" component is experimental and may be subject to breaking changes. To enable this experiment, please include `experimental: { images: { allowFutureImage: true } }` in your next.config.js file.`

### Your minimal, reproducible example

None

### Steps to reproduce

1. Create component with `import NextImage from 'next/future/image'`
2. Add this component to storybook
3. Run storybook but it just fails with the above error 

### Expected behavior

Storybook start normally

### How often does this bug happen?

Every time

### Platform

- Windows

### storybook-addon-next version

v 1.6.7

**Comment by DhiaPhntm** [comment] 2022-08-09 11:54
Same here - nextJS version 12.2.4

**Comment by dawidk92** [comment] 2022-08-23 09:52
Duplicate of https://github.com/RyanClementsHax/storybook-addon-next/issues/99 issue

**Comment by RyanClementsHax** [comment] 2022-09-22 13:06
Closing in favor of #99

**Closed** 2022-09-22 13:07 UTC
Labels: duplicate
