### ISSUE TITLE
Does not work on Next canary version 

### ISSUE THREAD

**Issue by ksielyov** [RyanClementsHax/storybook-addon-next#92] opened 2022-06-04 13:46 UTC
### Describe the bug

Storybook is started but gives the error:
```
530.manager.bundle.js:71222 
Warning: ReactDOM.render is no longer supported in React 18.
Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. 
Learn more: https://reactjs.org/link/switch-to-createroot
```

### Your minimal, reproducible example

Default config from docs

### Steps to reproduce

1. Use next version ```12.1.6```
2. It works
3. Update to ```12.1.7-canary.29```
4. It gives the above error

### Expected behavior

Working Storybook

### How often does this bug happen?

Every time

### Screenshots or Videos

![Снимок экрана 2022-06-04 в 18 44 46](https://user-images.githubusercontent.com/47862601/172003418-5fb0fc4f-d16b-48b1-88ca-97dfdf57cf72.png)

### Platform

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101
    Binaries:
      Node: 14.17.5
      npm: 7.21.1
      Yarn: 1.22.11
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.29
      react: 18.1.0
      react-dom: 18.1.0

### storybook-addon-next version

^1.6.6

### Additional context

Critical issue, can not work with storybook at next canary version

**Comment by RyanClementsHax** [comment] 2022-06-25 21:34
Thanks for opening this issue!

This is actually a duplicate of #95. The react error you are seeing is actually a red herring and is an issue with storybook with react 18.

**Closed by RyanClementsHax** 2022-06-25 21:34 UTC
